name: Upload Invoices to Azure Blob

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Blob
        run: |
          az storage blob upload-batch \
            --account-name stinvdocsdev \
            --destination documents \
            --source ./invoices \
            --overwrite true \
            --auth-mode login
